version: "3.3"
services:
  burger:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - my-net
    depends_on:
      - mongo
    volumes:
    - .:/burger
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: burger_user
      MONGO_INITDB_ROOT_PASSWORD: burger_pass

networks:
  my-net:
    driver: bridge